# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangologdb.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('function_name', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.PositiveIntegerField(choices=[(20, b'Info'), (30, b'Warning'), (10, b'Debug'), (40, b'Error'), (50, b'Critical')], db_index=True, default=50)),
                ('line_number', models.PositiveIntegerField(default=0)),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, default=b'root', max_length=200)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('function_name', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.PositiveIntegerField(choices=[(20, b'Info'), (30, b'Warning'), (10, b'Debug'), (40, b'Error'), (50, b'Critical')], db_index=True, default=50)),
                ('line_number', models.PositiveIntegerField(default=0)),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, default=b'root', max_length=200)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('args', djangologdb.utils.TupleField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exc_text', models.TextField(blank=True, null=True)),
                ('process', models.PositiveIntegerField(default=0)),
                ('process_name', models.CharField(blank=True, max_length=200, null=True)),
                ('thread', models.DecimalField(decimal_places=0, max_digits=21)),
                ('thread_name', models.CharField(blank=True, max_length=200, null=True)),
                ('extra', djangologdb.utils.JSONField(blank=True)),
                ('log_aggregate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangologdb.LogAggregate')),
            ],
            options={
                'verbose_name_plural': 'Log entries',
            },
        ),
    ]
